-- ============================================================================
-- SCHEMA FINAL - DASHBOARD CTO
-- Sistema completo con métricas operativas y gerenciales
-- ============================================================================

-- Habilitar extensión para UUIDs
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================================
-- 1. TABLA DE DESARROLLADORES
-- ============================================================================

CREATE TABLE IF NOT EXISTS developers (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    github_username TEXT UNIQUE NOT NULL,
    full_name TEXT NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================================================
-- 2. TABLA DE MÉTRICAS DIARIAS (Músculo y Disponibilidad)
-- ============================================================================

CREATE TABLE IF NOT EXISTS daily_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    developer_id UUID REFERENCES developers(id) ON DELETE CASCADE,
    date DATE NOT NULL,
    commits_count INT DEFAULT 0,
    lines_added INT DEFAULT 0,
    lines_deleted INT DEFAULT 0,
    repos_touched INT DEFAULT 0,
    last_activity_at TIMESTAMP WITH TIME ZONE,
    days_inactive INT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(developer_id, date) -- Evita duplicados diarios por dev
);

-- ============================================================================
-- 3. TABLA DE ISSUES (Velocidad, Entrega y Retrabajo)
-- ============================================================================

CREATE TABLE IF NOT EXISTS github_issues (
    github_issue_id BIGINT PRIMARY KEY, -- El ID real que viene de GitHub
    developer_id UUID REFERENCES developers(id) ON DELETE SET NULL,
    repository_name TEXT NOT NULL,
    title TEXT NOT NULL,
    state TEXT NOT NULL CHECK (state IN ('open', 'closed')),
    labels TEXT[] DEFAULT '{}', -- Arreglo de etiquetas (ej. ['bug', 'feature', 'rework'])
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    closed_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    lead_time_hours FLOAT GENERATED ALWAYS AS (
        EXTRACT(EPOCH FROM (closed_at - created_at)) / 3600
    ) STORED
);

-- ============================================================================
-- 4. TABLA DE ACTIVIDAD POR PROYECTO (Para Project Mix)
-- ============================================================================

CREATE TABLE IF NOT EXISTS project_activity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    repo_name TEXT NOT NULL,
    commits_count INT DEFAULT 0,
    issues_count INT DEFAULT 0,
    developers_count INT DEFAULT 0,
    lines_changed INT DEFAULT 0,
    project_priority TEXT CHECK (project_priority IN ('high', 'medium', 'low')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(date, repo_name)
);

-- ============================================================================
-- 5. TABLA DE LOGS DE EXTRACCIÓN
-- ============================================================================

CREATE TABLE IF NOT EXISTS extraction_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    extraction_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    status TEXT,
    developers_processed INT,
    issues_processed INT,
    records_inserted INT,
    records_updated INT,
    errors TEXT,
    duration_seconds INT
);

-- ============================================================================
-- ÍNDICES PARA RENDIMIENTO (PERFORMANCE)
-- ============================================================================

-- Índices en daily_metrics
CREATE INDEX IF NOT EXISTS idx_daily_metrics_date ON daily_metrics(date);
CREATE INDEX IF NOT EXISTS idx_daily_metrics_dev ON daily_metrics(developer_id);
CREATE INDEX IF NOT EXISTS idx_daily_metrics_date_inactive ON daily_metrics(date, days_inactive);
CREATE INDEX IF NOT EXISTS idx_daily_metrics_dev_date ON daily_metrics(developer_id, date);

-- Índices en github_issues
CREATE INDEX IF NOT EXISTS idx_issues_state ON github_issues(state);
CREATE INDEX IF NOT EXISTS idx_issues_closed_at ON github_issues(closed_at);
CREATE INDEX IF NOT EXISTS idx_issues_repo ON github_issues(repository_name);
CREATE INDEX IF NOT EXISTS idx_issues_developer ON github_issues(developer_id);
CREATE INDEX IF NOT EXISTS idx_issues_created_at ON github_issues(created_at);
CREATE INDEX IF NOT EXISTS idx_issues_labels ON github_issues USING GIN(labels);

-- Índices en project_activity
CREATE INDEX IF NOT EXISTS idx_project_activity_date ON project_activity(date);
CREATE INDEX IF NOT EXISTS idx_project_activity_repo ON project_activity(repo_name);

-- Índices en developers
CREATE INDEX IF NOT EXISTS idx_developers_github_username ON developers(github_username);
CREATE INDEX IF NOT EXISTS idx_developers_is_active ON developers(is_active);

-- Índices en extraction_logs
CREATE INDEX IF NOT EXISTS idx_extraction_logs_date ON extraction_logs(extraction_date DESC);

-- ============================================================================
-- VISTAS OPERATIVAS (7 WIDGETS TÉCNICOS)
-- ============================================================================

-- VISTA O1: Radar de Disponibilidad (Bench Watch)
CREATE OR REPLACE VIEW vw_bench_watch AS
SELECT 
    d.id as developer_id,
    d.full_name, 
    d.github_username,
    dm.days_inactive, 
    dm.last_activity_at,
    CASE 
        WHEN dm.days_inactive > 2 THEN '🔴 CRÍTICO'
        WHEN dm.days_inactive = 2 THEN '🟠 ALTO'
        WHEN dm.days_inactive = 1 THEN '🟡 MEDIO'
        ELSE '🟢 ACTIVO'
    END as status_bench
FROM developers d
LEFT JOIN daily_metrics dm ON d.id = dm.developer_id AND dm.date = CURRENT_DATE
WHERE d.is_active = TRUE
ORDER BY dm.days_inactive DESC NULLS LAST;

-- VISTA O2: Velocidad de Entrega (Throughput Diario)
CREATE OR REPLACE VIEW vw_throughput_daily AS
SELECT 
    DATE(closed_at) as date,
    COUNT(*) as issues_closed,
    ROUND(AVG(lead_time_hours)::numeric, 2) as avg_lead_time_h,
    COUNT(DISTINCT developer_id) as developers_activos
FROM github_issues
WHERE state = 'closed' 
AND closed_at >= CURRENT_DATE - INTERVAL '30 days'
AND closed_at IS NOT NULL
GROUP BY DATE(closed_at)
ORDER BY date DESC;

-- VISTA O3: Eficiencia por Desarrollador (Lead Time)
CREATE OR REPLACE VIEW vw_velocity_by_dev AS
SELECT 
    d.id as developer_id,
    d.github_username,
    d.full_name,
    COUNT(i.github_issue_id) as total_issues_closed,
    ROUND(AVG(i.lead_time_hours)::numeric, 2) as avg_lead_time_h,
    MIN(i.lead_time_hours) as best_lead_time_h,
    MAX(i.closed_at) as last_delivery
FROM developers d
LEFT JOIN github_issues i ON d.id = i.developer_id 
    AND i.state = 'closed' 
    AND i.closed_at >= CURRENT_DATE - INTERVAL '7 days'
WHERE d.is_active = TRUE
GROUP BY d.id, d.github_username, d.full_name
ORDER BY avg_lead_time_h ASC NULLS LAST;

-- VISTA O4: Volumen de Código (Code Volume)
CREATE OR REPLACE VIEW vw_code_volume_daily AS
SELECT 
    date,
    SUM(lines_added) as total_added,
    SUM(lines_deleted) as total_deleted,
    SUM(lines_added + lines_deleted) as total_churn,
    ROUND(AVG(lines_added::FLOAT / NULLIF(lines_deleted, 0))::numeric, 2) as add_delete_ratio
FROM daily_metrics
WHERE date >= CURRENT_DATE - INTERVAL '30 days'
GROUP BY date
ORDER BY date DESC;

-- VISTA O5: Índice de Foco (Context Switching)
CREATE OR REPLACE VIEW vw_focus_index AS
SELECT 
    d.github_username,
    d.full_name,
    dm.date,
    dm.repos_touched,
    dm.lines_added + dm.lines_deleted as code_volume,
    CASE 
        WHEN dm.repos_touched = 1 THEN '🟢 ENFOCADO'
        WHEN dm.repos_touched = 2 THEN '🟡 MODERADO'
        ELSE '🔴 DISPERSO'
    END as focus_status
FROM daily_metrics dm
JOIN developers d ON dm.developer_id = d.id
WHERE dm.date >= CURRENT_DATE - INTERVAL '7 days'
AND d.is_active = TRUE
ORDER BY dm.date DESC, dm.repos_touched DESC;

-- VISTA O6: Consistencia de Flujo (Commit Pulse)
CREATE OR REPLACE VIEW vw_commit_pulse AS
SELECT 
    d.id as developer_id,
    d.github_username,
    dm.date,
    dm.commits_count,
    LAG(dm.commits_count, 1) OVER (PARTITION BY d.id ORDER BY dm.date) as commits_prev_day,
    dm.commits_count - LAG(dm.commits_count, 1) OVER (PARTITION BY d.id ORDER BY dm.date) as commit_delta
FROM daily_metrics dm
JOIN developers d ON dm.developer_id = d.id
WHERE dm.date >= CURRENT_DATE - INTERVAL '14 days'
AND d.is_active = TRUE
ORDER BY d.github_username, dm.date DESC;

-- VISTA O7: Alerta de Tareas Estancadas (Stale Issues)
CREATE OR REPLACE VIEW vw_stale_issues AS
SELECT 
    i.github_issue_id,
    i.repository_name,
    i.title,
    d.full_name AS assignee,
    i.labels,
    EXTRACT(DAY FROM (NOW() - i.created_at))::INT AS days_open,
    i.created_at,
    CASE 
        WHEN EXTRACT(DAY FROM (NOW() - i.created_at)) > 7 THEN '🔴 CRÍTICO'
        WHEN EXTRACT(DAY FROM (NOW() - i.created_at)) > 3 THEN '🟠 URGENTE'
        ELSE '🟡 ATENCIÓN'
    END as urgency_level
FROM github_issues i
LEFT JOIN developers d ON i.developer_id = d.id
WHERE i.state = 'open' AND i.created_at < NOW() - INTERVAL '3 days'
ORDER BY days_open DESC;

-- ============================================================================
-- VISTAS GERENCIALES (5 KPIs EJECUTIVOS)
-- ============================================================================

-- VISTA M1: Throughput Semanal
CREATE OR REPLACE VIEW vw_kpi_throughput_semanal AS
WITH semanas AS (
    SELECT 
        DATE_TRUNC('week', closed_at)::DATE as semana,
        COUNT(*) as total_issues_cerrados,
        COUNT(DISTINCT developer_id) as devs_activos,
        ROUND(AVG(lead_time_hours)::numeric, 2) as avg_lead_time
    FROM github_issues
    WHERE state = 'closed' 
    AND closed_at >= CURRENT_DATE - INTERVAL '8 weeks'
    AND closed_at IS NOT NULL
    GROUP BY DATE_TRUNC('week', closed_at)::DATE
)
SELECT 
    semana,
    total_issues_cerrados,
    devs_activos,
    avg_lead_time,
    ROUND(
        (((total_issues_cerrados::FLOAT / NULLIF(LAG(total_issues_cerrados) OVER (ORDER BY semana), 0)) - 1) * 100)::numeric,
        2
    ) as variacion_porcentual
FROM semanas
ORDER BY semana DESC;

-- VISTA M2: Lead Time Tendencia
CREATE OR REPLACE VIEW vw_kpi_lead_time_tendencia AS
SELECT 
    DATE_TRUNC('week', closed_at)::DATE as semana,
    ROUND(AVG(lead_time_hours)::numeric, 2) as lead_time_promedio_h,
    MIN(lead_time_hours) as mejor_lead_time_h,
    MAX(lead_time_hours) as peor_lead_time_h,
    COUNT(*) as total_entregas,
    ROUND((AVG(lead_time_hours) / 24.0)::numeric, 2) as lead_time_dias
FROM github_issues
WHERE state = 'closed' 
AND closed_at >= CURRENT_DATE - INTERVAL '8 weeks'
AND closed_at IS NOT NULL
AND lead_time_hours > 0
GROUP BY DATE_TRUNC('week', closed_at)::DATE
ORDER BY semana DESC;

-- VISTA M3: Distribución de Esfuerzo (Project Mix)
CREATE OR REPLACE VIEW vw_project_mix_weekly AS
SELECT 
    repository_name,
    COUNT(*) as total_issues_closed,
    ROUND((COUNT(*) * 100.0 / SUM(COUNT(*)) OVER ())::numeric, 2) as percentage_of_effort,
    COUNT(DISTINCT developer_id) as developers_involved
FROM github_issues
WHERE state = 'closed' 
AND closed_at >= DATE_TRUNC('week', NOW())
AND closed_at IS NOT NULL
GROUP BY repository_name
ORDER BY total_issues_closed DESC;

-- VISTA M4: Tasa de Retrabajo
CREATE OR REPLACE VIEW vw_kpi_rework_rate AS
WITH issues_semana AS (
    SELECT 
        COUNT(*) as total_issues,
        SUM(CASE WHEN 'bug' = ANY(labels) OR 'rework' = ANY(labels) THEN 1 ELSE 0 END) as issues_rework
    FROM github_issues
    WHERE state = 'closed'
    AND closed_at >= DATE_TRUNC('week', NOW())
    AND closed_at IS NOT NULL
)
SELECT 
    total_issues,
    issues_rework,
    ROUND(((issues_rework::FLOAT / NULLIF(total_issues, 0)) * 100)::numeric, 2) as rework_rate_porcentaje,
    CASE 
        WHEN (issues_rework::FLOAT / NULLIF(total_issues, 0)) * 100 < 5 THEN '🟢 EXCELENTE'
        WHEN (issues_rework::FLOAT / NULLIF(total_issues, 0)) * 100 < 10 THEN '🟡 ACEPTABLE'
        ELSE '🔴 REQUIERE ATENCIÓN'
    END as calidad_status
FROM issues_semana;

-- VISTA M5: Utilización del Equipo
CREATE OR REPLACE VIEW vw_kpi_utilizacion_equipo AS
WITH estado_devs AS (
    SELECT 
        d.id,
        d.github_username,
        d.full_name,
        COALESCE(dm.days_inactive, 999) as dias_inactivo,
        CASE 
            WHEN COALESCE(dm.days_inactive, 999) <= 1 THEN 'ACTIVO'
            WHEN COALESCE(dm.days_inactive, 999) <= 3 THEN 'PARCIAL'
            ELSE 'BENCH'
        END as estado
    FROM developers d
    LEFT JOIN daily_metrics dm ON d.id = dm.developer_id AND dm.date = CURRENT_DATE
    WHERE d.is_active = TRUE
)
SELECT 
    COUNT(*) as total_desarrolladores,
    SUM(CASE WHEN estado = 'ACTIVO' THEN 1 ELSE 0 END) as devs_activos,
    SUM(CASE WHEN estado = 'PARCIAL' THEN 1 ELSE 0 END) as devs_parciales,
    SUM(CASE WHEN estado = 'BENCH' THEN 1 ELSE 0 END) as devs_bench,
    ROUND(((SUM(CASE WHEN estado = 'ACTIVO' THEN 1 ELSE 0 END)::FLOAT / NULLIF(COUNT(*), 0)) * 100)::numeric, 2) as tasa_utilizacion
FROM estado_devs;

-- VISTA GERENCIAL CONSOLIDADA: Gran Tablero Semanal (KPIs Consolidados)
CREATE OR REPLACE VIEW vw_managerial_kpis_weekly AS
WITH weekly_issues AS (
    SELECT * FROM github_issues 
    WHERE state = 'closed' 
    AND closed_at >= DATE_TRUNC('week', NOW())
    AND closed_at IS NOT NULL
),
active_devs AS (
    SELECT COUNT(*) as total_devs FROM developers WHERE is_active = TRUE
),
benched_devs AS (
    SELECT COUNT(*) as benched_count FROM vw_bench_watch WHERE days_inactive > 2
)
SELECT 
    -- M1: Throughput
    (SELECT COUNT(*) FROM weekly_issues) AS m1_throughput_total_entregas,
    
    -- M2: Lead Time
    COALESCE((SELECT ROUND(AVG(lead_time_hours)::numeric, 2) FROM weekly_issues), 0) AS m2_lead_time_promedio_h,
    
    -- M3: Project Mix (Top repo)
    (SELECT repository_name FROM vw_project_mix_weekly LIMIT 1) as m3_top_proyecto,
    (SELECT percentage_of_effort FROM vw_project_mix_weekly LIMIT 1) as m3_top_proyecto_pct,
    
    -- M4: Tasa de Retrabajo
    COALESCE(
        ROUND(((SELECT COUNT(*) FROM weekly_issues WHERE 'bug' = ANY(labels) OR 'rework' = ANY(labels)) * 100.0 / NULLIF((SELECT COUNT(*) FROM weekly_issues), 0))::numeric, 2), 
    0) AS m4_tasa_retrabajo_pct,
    
    -- M5: Utilización / Bench Rate
    COALESCE(
        ROUND(((1.0 - (SELECT benched_count FROM benched_devs)::FLOAT / NULLIF((SELECT total_devs FROM active_devs), 0)) * 100)::numeric, 2), 
    0) AS m5_utilizacion_equipo_pct;

-- ============================================================================
-- FUNCIONES RPC
-- ============================================================================

-- Función: Generar reporte ejecutivo completo
CREATE OR REPLACE FUNCTION generar_reporte_ejecutivo()
RETURNS JSON AS $$
DECLARE
    reporte JSON;
BEGIN
    SELECT json_build_object(
        'fecha', CURRENT_DATE,
        'periodo', 'Semana ' || TO_CHAR(CURRENT_DATE, 'WW/YYYY'),
        
        'kpi_throughput', json_build_object(
            'valor', (SELECT m1_throughput_total_entregas FROM vw_managerial_kpis_weekly),
            'meta', 'Incremental'
        ),
        
        'kpi_lead_time', json_build_object(
            'valor_horas', (SELECT m2_lead_time_promedio_h FROM vw_managerial_kpis_weekly),
            'meta_horas', 24,
            'cumple', (SELECT m2_lead_time_promedio_h FROM vw_managerial_kpis_weekly) <= 24
        ),
        
        'kpi_project_mix', json_build_object(
            'top_proyecto', (SELECT m3_top_proyecto FROM vw_managerial_kpis_weekly),
            'porcentaje', (SELECT m3_top_proyecto_pct FROM vw_managerial_kpis_weekly)
        ),
        
        'kpi_calidad', json_build_object(
            'rework_rate', (SELECT m4_tasa_retrabajo_pct FROM vw_managerial_kpis_weekly),
            'meta', 10,
            'cumple', (SELECT m4_tasa_retrabajo_pct FROM vw_managerial_kpis_weekly) < 10
        ),
        
        'kpi_utilizacion', json_build_object(
            'tasa', (SELECT m5_utilizacion_equipo_pct FROM vw_managerial_kpis_weekly),
            'meta', 85,
            'cumple', (SELECT m5_utilizacion_equipo_pct FROM vw_managerial_kpis_weekly) >= 85
        )
    ) INTO reporte;
    
    RETURN reporte;
END;
$$ LANGUAGE plpgsql;

-- Función: Calcular score de desarrollador
CREATE OR REPLACE FUNCTION calcular_score_desarrollador(dev_id UUID)
RETURNS JSON AS $$
DECLARE
    score JSON;
    issues_count INT;
    avg_lead FLOAT;
    dias_inactivo INT;
BEGIN
    -- Obtener métricas del desarrollador (última semana)
    SELECT 
        COUNT(*),
        AVG(lead_time_hours)
    INTO issues_count, avg_lead
    FROM github_issues
    WHERE developer_id = dev_id
    AND state = 'closed'
    AND closed_at >= CURRENT_DATE - INTERVAL '7 days';
    
    -- Obtener días inactivos
    SELECT days_inactive INTO dias_inactivo
    FROM daily_metrics
    WHERE developer_id = dev_id
    AND date = CURRENT_DATE;
    
    -- Construir score
    SELECT json_build_object(
        'issues_cerrados', COALESCE(issues_count, 0),
        'lead_time_promedio', COALESCE(avg_lead, 0),
        'dias_inactivo', COALESCE(dias_inactivo, 0),
        'score_velocidad', CASE WHEN avg_lead < 24 THEN 100 ELSE GREATEST(0, 100 - (avg_lead - 24) * 2) END,
        'score_productividad', LEAST(100, issues_count * 10)
    ) INTO score;
    
    RETURN score;
END;
$$ LANGUAGE plpgsql;

-- ============================================================================
-- TRIGGERS
-- ============================================================================

-- Función para actualizar timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Triggers para developers
DROP TRIGGER IF EXISTS update_developers_updated_at ON developers;
CREATE TRIGGER update_developers_updated_at
    BEFORE UPDATE ON developers
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Triggers para daily_metrics
DROP TRIGGER IF EXISTS update_daily_metrics_updated_at ON daily_metrics;
CREATE TRIGGER update_daily_metrics_updated_at
    BEFORE UPDATE ON daily_metrics
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Triggers para github_issues
DROP TRIGGER IF EXISTS update_github_issues_updated_at ON github_issues;
CREATE TRIGGER update_github_issues_updated_at
    BEFORE UPDATE ON github_issues
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- SEGURIDAD DE NIVEL DE FILA (RLS)
-- ============================================================================

ALTER TABLE developers ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_metrics ENABLE ROW LEVEL SECURITY;
ALTER TABLE github_issues ENABLE ROW LEVEL SECURITY;
ALTER TABLE project_activity ENABLE ROW LEVEL SECURITY;

-- Política: Todos los usuarios autenticados pueden leer
CREATE POLICY "Lectura general para usuarios autenticados" ON developers
    FOR SELECT TO authenticated USING (true);

CREATE POLICY "Lectura general para usuarios autenticados" ON daily_metrics
    FOR SELECT TO authenticated USING (true);

CREATE POLICY "Lectura general para usuarios autenticados" ON github_issues
    FOR SELECT TO authenticated USING (true);

CREATE POLICY "Lectura general para usuarios autenticados" ON project_activity
    FOR SELECT TO authenticated USING (true);

-- Nota: El rol 'service_role' se salta el RLS por defecto
-- El script de extracción usando SERVICE_ROLE_KEY podrá insertar sin problemas

-- ============================================================================
-- COMENTARIOS Y DOCUMENTACIÓN
-- ============================================================================

COMMENT ON TABLE developers IS 'Perfiles de desarrolladores del equipo';
COMMENT ON TABLE daily_metrics IS 'Métricas diarias de actividad de código (músculo y disponibilidad)';
COMMENT ON TABLE github_issues IS 'Issues de GitHub para tracking de velocidad, entrega y retrabajo';
COMMENT ON TABLE project_activity IS 'Actividad agregada por proyecto para Project Mix';
COMMENT ON TABLE extraction_logs IS 'Logs de ejecución del extractor de métricas';

COMMENT ON VIEW vw_bench_watch IS 'O1: Radar de Disponibilidad - Detecta desarrolladores sin asignación';
COMMENT ON VIEW vw_throughput_daily IS 'O2: Velocidad de Entrega - Issues cerrados por día';
COMMENT ON VIEW vw_velocity_by_dev IS 'O3: Eficiencia por Desarrollador - Lead time promedio';
COMMENT ON VIEW vw_code_volume_daily IS 'O4: Volumen de Código - Líneas generadas por IA';
COMMENT ON VIEW vw_focus_index IS 'O5: Índice de Foco - Context switching entre repos';
COMMENT ON VIEW vw_commit_pulse IS 'O6: Consistencia de Flujo - Ritmo de commits';
COMMENT ON VIEW vw_stale_issues IS 'O7: Tareas Estancadas - Issues abiertos > 3 días';

COMMENT ON VIEW vw_managerial_kpis_weekly IS 'Dashboard Gerencial - 5 KPIs consolidados para reuniones ejecutivas';

-- ============================================================================
-- FIN DEL SCHEMA
-- ============================================================================
